#!/bin/bash

python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 0 --world-size 10 --backend ccl --sync_compressor &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 1 --world-size 10 --backend ccl --sync_compressor &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 2 --world-size 10 --backend ccl --sync_compressor &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 3 --world-size 10 --backend ccl --sync_compressor &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 4 --world-size 10 --backend ccl --sync_compressor &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 5 --world-size 10 --backend ccl --sync_compressor &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 6 --world-size 10 --backend ccl --sync_compressor &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 7 --world-size 10 --backend ccl --sync_compressor &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 8 --world-size 10 --backend ccl --sync_compressor &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json             --log_dir log/fixed_cr/feature/CR=16/K=1/TRIAL=0 --compression_type feature --comp_ratio 16 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3                 --train-iters 256 --rank 9 --world-size 10 --backend ccl --sync_compressor &
wait

